# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-23 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['top_fix', 'created']},
        ),
        migrations.AddField(
            model_name='topic',
            name='top_fix',
            field=models.BooleanField(default=False),
        ),
    ]
