# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-23 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20180223_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['top_fix', '-created']},
        ),
    ]
