# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-24 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_remove_topic_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='Закрытая'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='top_fix',
            field=models.BooleanField(default=False, verbose_name='Закрепленая'),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set([('title', 'created')]),
        ),
    ]
