# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-21 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_auto_20180224_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
